spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

# 로깅 레벨 설정
# 캐시의 조회, 저장, 삭제와 같은 작업에 대한 모든 세부 정보가 로그로 기록됨
# 해당 설정은 org.springframework.cache 패키지에만 적용
logging:
  level:
    org.springframework.cache: trace

