spring:
  config:
    import: aws-parameterstore:/woozuda/parameter_release/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
#  datasource:
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
#      idle-timeout: 600000 # 10분
#      max-lifetime: 1800000 # 30분
#      keepalive-time: 45000 # 45초. HikariCP가 매 라운드마다 1개씩 ping

management:
  server:
    port: "${actuator_port}"
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true #default

server:
  tomcat:
    keep-alive-timeout: 5s

logging:
  config: "classpath:./logback-release.xml"
