spring:
  config:
    import: aws-parameterstore:/woozuda/parameter_release/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

management:
  server:
    port: "${actuator_port}"
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true #default

logging:
  config: "classpath:./logback-release.xml"
