spring:
  application:
    name: backend

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${database_url}"
    username: "${database_username}"
    password: "${database_password}"

  jwt:
    secret: "${jwt_hashcode}"

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: "${oauth2_naver_id}"
            client-secret: "${oauth2_naver_secret}"
            redirect-uri: "${oauth2_naver_redirect}"
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: "${oauth2_google_id}"
            client-secret: "${oauth2_google_secret}"
            redirect-uri: "${oauth2_naver_redirect}"
            authorization-grant-type: authorization_code
            scope: profile, email
          kakao:
            client-name: kakao
            client-id: "${oauth2_kakao_id}"
            client-secret: "${oauth2_kakao_secret}"
            redirect-uri: "${oauth2_kakao_redirect}"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      access-key: "${s3_access_key}"
      secret-key: "${s3_secret_key}"
      bucket-name : "${s3_bucket_name}"
  ncp:
    clova-studio:
      question-creator:
        url: "${question_creator_url}"
        api-key: "${question_creator_api_key}"
        request-id: "${question_creator_request_id}"

openai:
  api:
    key: openai_key  # 환경 변수에서 OPENAI_API_KEY를 가져옵니다.
    url: openai_url
    chat:
      options:
        model: gpt-3.5-turbo  # 사용할 AI 모델 (예: gpt-3.5-turbo)
        temperature: 0.7  # 생성되는 텍스트의 다양성 정도를 조절하는 파라미터 (0.0 ~ 1.0)

clova:
  api:
    key: temp_key # "${clova.api.key}"
    url: temp_url # "${clova.api.url}"
    rid: temp_rid # "${clova.api.rid}"

allow-ips:
  127.0.0.1

aes:
  password: "${aes_password}"