services:
  springboot:
    container_name: springboot-app
    image: ${ECR_IMAGE}
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILE: release
      LOG_PATH_PREFIX: ${LOG_PATH_PREFIX}
      HOST_LOG_PATH_PREFIX: ${HOST_LOG_PATH_PREFIX}
    volumes:
      - ${HOST_LOG_PATH_PREFIX}/spring-boot:${LOG_PATH_PREFIX}
    networks:
      - backend
    depends_on:
      - promtail

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    environment:
      HOST_LOG_PATH_PREFIX: ${HOST_LOG_PATH_PREFIX}
    volumes:
      - ${HOST_LOG_PATH_PREFIX}:${HOST_LOG_PATH_PREFIX}
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: ["-config.file=/etc/promtail/config.yml"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
