name: Build and Test

on:
  pull_request:
    branches:
      - develop
      - release
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    if: >
      !(github.base_ref == 'develop' && github.head_ref == 'release') &&
      !(github.base_ref == 'release' && github.head_ref == 'develop')

    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Java 환경 설정
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Gradle 환경 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. 빌드 테스트
      - name: Build and Test
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
        shell: bash

      # 5. 빌드 실패 시 코멘트
      - name: Comment on PR if Build Fail
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: `:x: 빌드 테스트가 실패했습니다. 자세한 내용은 Github Actions 탭에서 확인해주세요`
            });
